CREATE DATABASE IF NOT EXISTS vku_field_survey
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE vku_field_survey;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS api_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS surveys (
  id CHAR(36) PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  building VARCHAR(120) NOT NULL,
  floor VARCHAR(40) NOT NULL,
  room VARCHAR(80) NOT NULL,
  category VARCHAR(80) NOT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  notes TEXT NULL,
  photo LONGTEXT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  status ENUM('PENDING_SYNC','SYNCED') NOT NULL DEFAULT 'SYNCED',
  created_at DATETIME NOT NULL,
  saved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_surveys_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_surveys_user_created (user_id, created_at)
) ENGINE=InnoDB;
